require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe IntervalsController do

  def mock_interval(stubs={})
    @mock_interval ||= mock_model(Interval, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all intervals as @intervals" do
      Interval.stub(:all) { [mock_interval] }
      get :index
      assigns(:intervals).should eq([mock_interval])
    end
  end

  describe "GET show" do
    it "assigns the requested interval as @interval" do
      Interval.stub(:find).with("37") { mock_interval }
      get :show, :id => "37"
      assigns(:interval).should be(mock_interval)
    end
  end

  describe "GET new" do
    it "assigns a new interval as @interval" do
      Interval.stub(:new) { mock_interval }
      get :new
      assigns(:interval).should be(mock_interval)
    end
  end

  describe "GET edit" do
    it "assigns the requested interval as @interval" do
      Interval.stub(:find).with("37") { mock_interval }
      get :edit, :id => "37"
      assigns(:interval).should be(mock_interval)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created interval as @interval" do
        Interval.stub(:new).with({'these' => 'params'}) { mock_interval(:save => true) }
        post :create, :interval => {'these' => 'params'}
        assigns(:interval).should be(mock_interval)
      end

      it "redirects to the created interval" do
        Interval.stub(:new) { mock_interval(:save => true) }
        post :create, :interval => {}
        response.should redirect_to(interval_url(mock_interval))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interval as @interval" do
        Interval.stub(:new).with({'these' => 'params'}) { mock_interval(:save => false) }
        post :create, :interval => {'these' => 'params'}
        assigns(:interval).should be(mock_interval)
      end

      it "re-renders the 'new' template" do
        Interval.stub(:new) { mock_interval(:save => false) }
        post :create, :interval => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interval" do
        Interval.stub(:find).with("37") { mock_interval }
        mock_interval.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :interval => {'these' => 'params'}
      end

      it "assigns the requested interval as @interval" do
        Interval.stub(:find) { mock_interval(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:interval).should be(mock_interval)
      end

      it "redirects to the interval" do
        Interval.stub(:find) { mock_interval(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(interval_url(mock_interval))
      end
    end

    describe "with invalid params" do
      it "assigns the interval as @interval" do
        Interval.stub(:find) { mock_interval(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:interval).should be(mock_interval)
      end

      it "re-renders the 'edit' template" do
        Interval.stub(:find) { mock_interval(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interval" do
      Interval.stub(:find).with("37") { mock_interval }
      mock_interval.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the intervals list" do
      Interval.stub(:find) { mock_interval }
      delete :destroy, :id => "1"
      response.should redirect_to(intervals_url)
    end
  end

end
